model_name: lightgbm

model_params:
  n_estimators: 200
  learning_rate: 0.05
  max_depth: -1           # 不限制深度
  min_data_in_leaf: 10    # 叶子节点最小样本数
  min_gain_to_split: 0    # 最小分裂增益
  subsample: 0.8
  colsample_bytree: 0.8